import turtle
win = turtle.Screen()
pen = turtle.Turtle()
win.setup(1200, 700)
win.title("SWEET HOME")
def drawHouse(target, x, y, body_color, body_width, body_height, roof_color, roof_width, roof_height):
    target.penup()
    target.goto(x, y)
    target.fillcolor(body_color)
    target.begin_fill()
    target.setheading(0)
    target.forward(body_width/2)
    target.right(90)
    target.forward(body_height)
    target.right(90)
    target.forward(body_width)
    target.right(90)
    target.forward(body_height)
    target.right(90)
    target.forward(body_width/2)
    target.end_fill()
    target.fillcolor(roof_color)
    target.begin_fill()
    target.forward(roof_width/2)
    target.goto(x, y+roof_height)
    target.goto(x-roof_width/2, y)
    target.end_fill()
    target.penup()
    target.goto(x, y)
drawHouse(pen, 0, 0, 'black', 200, 200, 'red', 300, 150)