from random import *
users = list(range(1, 21))
shuffle(users)
chicken = choice(users)
users.remove(chicken)
coffee = sample(users, 3)
print("--- 당첨자 발표 ---")
print(f"치킨 당첨자 : {chicken}")
print(f"커피 당첨자 : {coffee}")
print("--- 축하합니다 ---")